import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, HeartHandshake, Leaf, Sparkles, Target, Users } from "lucide-react";
import { Link } from "wouter";
import Navbar from "@/components/borla/Navbar";
import Footer from "@/components/borla/Footer";

const values = [
  { icon: Target, title: "Reliability is a service", body: "A pickup window should be something a family or a shop can actually plan the day around." },
  { icon: HeartHandshake, title: "Collectors deserve clarity", body: "We make routes, payments, and expectations clearer for the people doing the work." },
  { icon: Leaf, title: "Clean streets are shared work", body: "Better coordination makes the healthier choice easier for every neighborhood." },
];

export default function About() {
  return (
    <div className="min-h-screen bg-[#f7f6f0] text-[#16352c]"><Navbar /><main>
      <section className="relative overflow-hidden border-b border-[#dfe4db] px-5 pb-16 pt-16 sm:px-8 lg:pb-24 lg:pt-24"><div className="cc-grid-lines pointer-events-none absolute inset-0 opacity-80" /><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="relative mx-auto max-w-4xl text-center"><p className="mx-auto inline-flex items-center gap-2 rounded-full border border-[#ccd8cc] bg-white/55 px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#557066]"><span className="h-2 w-2 rounded-full bg-[#f07b5c]" /> Our point of view</p><h1 className="cc-display mt-7 text-[clamp(3.5rem,8vw,7rem)] leading-[0.88]">A cleaner city starts with <em className="text-[#e77b5e]">better coordination.</em></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-[#5d6b62] sm:text-lg">CleanConnect is building the everyday infrastructure that makes waste collection feel dependable, visible, and worth trusting.</p></motion.div><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25, duration: 0.8 }} className="relative mx-auto mt-14 grid max-w-6xl gap-3 lg:grid-cols-[1.15fr_0.85fr]"><div className="relative min-h-[360px] overflow-hidden rounded-[26px] bg-[#dfe8dc]"><img src="https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1600&q=85" alt="Clean public space in a Ghanaian city" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[#16352c]/24" /><div className="absolute bottom-5 left-5 rounded-full bg-[#f7f6f0]/90 px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.17em] text-[#16352c]">Built for the everyday</div></div><div className="rounded-[26px] bg-[#f0c66c] p-7 sm:p-9"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#755e20]">The short version</p><p className="cc-display mt-9 text-4xl leading-[0.94] text-[#16352c]">Less guesswork for homes. More dignity for the people keeping them clean.</p><div className="mt-10 flex items-center gap-3 border-t border-[#af922f]/50 pt-5 text-sm font-semibold text-[#5e572f]"><Users size={18} /> Local routes, designed around real streets</div></div></motion.div></section>
      <section className="border-b border-[#dfe4db] bg-white px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[0.78fr_1.22fr]"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-[#d56f55]">Why we started</p><h2 className="cc-display mt-3 text-4xl leading-[0.95] sm:text-5xl">Waste collection should not be a daily mystery.</h2></div><div className="space-y-5 text-sm leading-7 text-[#69776e]"><p>Across Ghanaian communities, households and businesses have learned to work around uncertain collection. A bin goes out early, a truck may arrive later, and everyone keeps one eye on the street.</p><p>CleanConnect began with a straightforward idea: organize the route, show the window, make payment simple, and treat the collector as a partner in the system.</p><p>We are starting with the neighborhoods we know, learning from the people who live and work there, and expanding one dependable route at a time.</p><Link href="/#coverage" className="inline-flex items-center gap-2 pt-2 font-bold text-[#16352c] underline decoration-[#f07b5c] decoration-2 underline-offset-4">See where we operate <ArrowRight size={16} /></Link></div></div></section>
      <section className="border-b border-[#dfe4db] bg-[#eef2eb] px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-6xl"><div className="max-w-xl"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.22em] text-[#d56f55]">What guides us</p><h2 className="cc-display mt-3 text-4xl leading-[0.95] sm:text-5xl">The work is logistical. The impact is human.</h2></div><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }} variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="mt-12 grid gap-3 md:grid-cols-3">{values.map(({ icon: Icon, title, body }) => <motion.article key={title} variants={{ hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55 } } }} className="border-t-2 border-[#c4d1c6] pt-5"><Icon size={22} className="text-[#e77b5e]" strokeWidth={1.7} /><h3 className="mt-9 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#69776e]">{body}</p></motion.article>)}</motion.div></div></section>
      <section className="bg-white px-5 py-14 sm:px-8 lg:py-20"><div className="mx-auto max-w-6xl overflow-hidden rounded-[28px] bg-[#16352c] px-6 py-12 text-center text-[#f7f6f0] sm:px-12"><Sparkles className="mx-auto text-[#f0c66c]" size={25} /><h2 className="cc-display mt-6 text-4xl leading-[0.95] sm:text-6xl">Ready for a more predictable week?</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-[#c1d0c3]">Find your neighborhood route and see what CleanConnect can take off your plate.</p><Link href="/#coverage" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#f0c66c] px-6 py-3.5 text-sm font-bold text-[#16352c]">Check coverage <ArrowUpRight size={17} /></Link></div></section>
    </main><Footer /></div>
  );
}
